version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerceuser
      POSTGRES_PASSWORD: ecommercepass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: django-insecure-%#en!j)rk9f(^w=_t*-pw0wht-t7d-(9+uy-n!=p*us3z0*-fs
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      CORS_ALLOW_ALL_ORIGINS: False
      CORS_ALLOWED_ORIGINS: localhost,127.0.0.1
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerceuser
      POSTGRES_PASSWORD: ecommercepass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
  media_data:
  static_data:
