# Generated by Django 5.0.2 on 2024-02-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('accessory', 'Accessory')], default='phone', max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='upload/products/')),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('in_stock', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
