# Generated by Django 5.0.2 on 2024-02-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='battery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='camera',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='cpu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='dimensions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='memory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='weight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
