# Generated by Django 5.0.2 on 2024-02-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_bill_alter_phone_product_accessory_billitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
