# Generated by Django 5.0.4 on 2024-06-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_billitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
    ]
